# Generated by Django 5.1.7 on 2025-03-20 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="catalogo_cuentaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, verbose_name="nombre")),
                (
                    "codigo_agrupador",
                    models.CharField(max_length=50, verbose_name="codigo agrupador"),
                ),
                ("nivel", models.IntegerField(verbose_name="nivel")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "usuario_creacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creacion_catalogo_cuenta",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario de Creación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catalogo de Cuenta",
                "verbose_name_plural": "Catalogo de Cuentas",
                "db_table": "catalogo_cuenta",
            },
        ),
    ]
